// <auto-generated />
using System;
using DistSysACW.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DistSysACW.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20200329013244_Logging")]
    partial class Logging
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("DistSysACW.Models.Log", b =>
                {
                    b.Property<string>("LogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogDateTime");

                    b.Property<string>("LogString");

                    b.Property<string>("UserApiKey");

                    b.HasKey("LogId");

                    b.HasIndex("UserApiKey");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DistSysACW.Models.Log_Archives", b =>
                {
                    b.Property<string>("LogId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("LogDateTime");

                    b.Property<string>("LogString");

                    b.HasKey("LogId");

                    b.ToTable("LogArchives");
                });

            modelBuilder.Entity("DistSysACW.Models.User", b =>
                {
                    b.Property<string>("ApiKey")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Role");

                    b.Property<string>("UserName");

                    b.HasKey("ApiKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DistSysACW.Models.Log", b =>
                {
                    b.HasOne("DistSysACW.Models.User")
                        .WithMany("Logs")
                        .HasForeignKey("UserApiKey");
                });
#pragma warning restore 612, 618
        }
    }
}
